name: 'action-checksec'
description: 'cheka cheka'
inputs:
  file:
    description: 'file'
    required: true

runs:
  using: "composite"
  steps: 
    - uses: actions/download-artifact@v2

    - name: run checksec on artifact
      run: |
        wget -q https://github.com/slimm609/checksec.sh/archive/2.4.0.tar.gz
        tar xzf 2.4.0.tar.gz
        ls -la
        checksec.sh-2.4.0/checksec --output=json --file=${{ file }}
