name: docker-compose-test
on: 
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: shellcheck
        run: docker-compose run shellcheck
      - name: ubuntu checksec
        run: docker-compose run checksec-ubuntu
      - name: arch checksec
        run: docker-compose run checksec-arch